backbone:
  config: mit_b1
  stride: [4, 2, 2, 1]
  comments: BRATS medical imaging dataset

dataset:
  root_dir: data/BRATS/imageSlice
  slice_split: [15500, 27435]
  num_classes: 2
  crop_size: 320
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

work_dir:
  dir: work_dir_brats
  ckpt_dir: checkpoints
  pred_dir: predictions
  segs_dir: segs
  tb_logger_dir: tb_logger

train:
  split: train
  samples_per_gpu: 128 # 4,        8,      16,     32,     64,     128
  max_iters: 37176 #    1189625,  594813, 297406, 148703, 74352, 37176
  cam_iters: 500
  eval_iters: 500
  log_iters: 200
  num_workers: 8

cam:
  bkg_score: 0.45
  high_thre: 0.55
  low_thre: 0.35
  aff_thre: 0.4
  scales: [1, 0.5, 1.5]

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 500
  warmup_ratio: 1e-6
  power: 1.0
